name: publico
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.0
  equatable: ^2.0.3
  file_picker: ^4.2.3
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_speed_dial: ^4.6.6
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http: ^0.13.4
  path_provider: ^2.0.7
  sqflite_sqlcipher: ^2.1.0
  uuid: ^3.0.5
  video_player: ^2.2.7
  video_thumbnail: ^0.4.3

dev_dependencies:
  analyzer: ^2.7.0
  bloc_test: ^8.5.0
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
